version: '4.41.2'
services:
  database: #Base de datos
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data #para guardar el volumen de datos

  pgadmin:    #Cliente grafico  para observar la base de datos
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
